name: Bug Report
description: If you encounter an issue whilst using our app, please use this template to help improve the app.
labels: ["🐛 Bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](https://github.com/ciderapp/Remote-iOS-BugTracker/issues) for a bug report that matches the one I want to file, without success.
          required: true
  - type: input
    attributes:
      label: Build Details
      description: What testflight version are you currently using? You can find this in the testflight app on your device.
    validations:
      required: true
  - type: input
    attributes:
      label: Cider Version
      description: What version of Cider are you using? You can find your build details from [this guide](https://github.com/ciderapp/Sabiiro-BugTracker/blob/main/docs/FINDING_VERSION.md).
      placeholder: "e.g. Cider 2.0.1"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug you encountered. Tell us what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: replication
    attributes:
      label: Steps to Reproduce
      description: How did you produce this bug, tell us how you did it so we can do it ourselves.
      placeholder: 1. Clicked on...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    id: uid
    attributes:
      label: Connect Device ID
      description: Helps us determine what version you are using (optional)
    validations:
      required: false
